language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: cd valuebot && python importexcelsheet.py && python createdataframe.py && python makedatabase.py && python updatedatabase.py && python dumpdatabase.py
