language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: 
  - python /valuebot/importexcelsheet.py
  - python /valuebot/createdataframe.py
  - python /valuebot/makedatabase.py
  - python /valuebot/updatedatabase.py
  - python /valuebot/dumpdatabase.py
